#!/system/bin/sh
#
LOG="log -p i -t PP"
# http://patorjk.com/software/taag/
# escape stuff like backquotes (`) and \ at end of lines with \
$LOG "
              _/                      _/
     _/_/_/  _/    _/_/    _/  _/_/        _/_/    _/    _/    _/_/_/
  _/    _/  _/  _/    _/  _/_/      _/  _/    _/  _/    _/  _/_/
 _/    _/  _/  _/    _/  _/        _/  _/    _/  _/    _/      _/_/
  _/_/_/  _/    _/_/    _/        _/    _/_/      _/_/_/  _/_/_/
     _/
_/_/

     _/_/_/                            _/            _/      _/_/
  _/          _/_/_/  _/_/_/      _/_/_/    _/_/_/  _/    _/
 _/  _/_/  _/    _/  _/    _/  _/    _/  _/    _/  _/  _/_/_/_/
_/    _/  _/    _/  _/    _/  _/    _/  _/    _/  _/    _/
 _/_/_/    _/_/_/  _/    _/    _/_/_/    _/_/_/  _/    _/


"
#
echo "build-info:"
cat /system/build.prop
echo ""
