#!/system/bin/sh
#
LOG="log -p i -t PP"
# http://patorjk.com/software/taag/
# escape stuff like backquotes (`) and \ at end of lines with \
$LOG "
   (_)___  ____ ____  ____  (_)___  __  _______
  / / __ \/ __ `/ _ \/ __ \/ / __ \/ / / / ___/
 / / / / / /_/ /  __/ / / / / /_/ / /_/ (__  ) 
/_/_/ /_/\__, /\___/_/ /_/_/\____/\__,_/____/  
        /____/                                 
    _      __             _ 
   (_)____/ /_____ ______(_)
  / / ___/ __/ __ `/ ___/ / 
 / (__  ) /_/ /_/ / /  / /  
/_/____/\__/\__,_/_/  /_/   
                            
"
#
echo "build-info:"
cat /system/build.prop
echo ""
