#!/system/bin/sh
# 2011-01-13 Firerat 
# check /cache size and set dexopt-data-only if too 'small'

experimental=0

# setup busybox aliases
alais mount="busybox mount"
alias grep="busybox grep"
alias sed="busybox sed"
alias install="busybox install"
alias printf="busybox printf"
alias awk="busybox awk"
alias mv="busybox mv"
alias du="busybox du"

# 35mb in bytes
MinCacheSize=36700160

# get cache size ( bytes ) from /proc/mtd 
CacheSizeBytes=$(printf %d `awk '/cache/ {print "0x"$2}' /proc/mtd`)

CheckSysDexSize ()
{
# my system dex is 24.8 mb ( would be less if I removed the IME bloat )
# this would fit a 1.33.0013d cache size of 27mb
# after a firstboot we can find the dex size
# but it might get complicated if system(google) apps are added later
# i.e. it may 'bootloop'
# Avoid this with experimental var, this way only those who "understand" will turn it on
# at least until I bloat this even more, to account for new apks/jars on system

SysDexSize=$(du -c /data/dalvik-cache/system@* |awk '/total/ {print $1 * 1024}')
SafetyMargin=1048576 # 1mb saftey margin
FreeCacheSize=$(df |awk '$6 == "/cache" {print $4 * 1024}')

if [ "$SysDexSize" = "0" ];
then
    # either it is the first boot or we already moved dex
    TestCacheSize
elif [ "`expr $SysDexSize + $SafetyMargin`" -lt "$FreeCacheSize" ];
then
    sysdexOnCache
    # hmm, if they didn't wipe system dex might be artifically too small
    # could get round this by including a firstboot.sh to clean up dex
    mv /data/dalvik-cache/system@* /cache/dalvik-cache/
else
    # system dex won't fit on /cache, so force it to stay on data
    dataOnlyDex
fi
return
}

mountsystem ()
{
opt=$1
if [ "`awk '$2 == "/system" {gsub(/,/," ,");print $4}' /proc/mounts`" != "$opt" ]; 
then
    mount -o ${opt},remount /system
fi
return
}

dataOnlyDex ()
{
# set the build.prop up to keep system dex on data
if [ "$(grep -q "dalvik.vm.dexopt-data-only=1" /system/build.prop;echo $?)" != "0" ];
then
    mountsystem rw
    # make sure build.prop is clean
    sed '/dalvik.vm.dexopt-data-only/ d' -i /system/build.prop
    echo "dalvik.vm.dexopt-data-only=1" >> /system/build.prop
    mountsystem ro
fi
return
}

sysdexOnCache ()
{
# make sure build.prop is clean, so system dex will go to /cache
if [ "$(grep -q "dalvik.vm.dexopt-data-only=1" /system/build.prop;echo $?)" = "0" ];
then
    mountsystem rw
    sed '/dalvik.vm.dexopt-data-only/ d' -i /system/build.prop
    mountsystem ro
fi
# need to make sure dir exists
if [ ! -d "/cache/dalvik-cache" ];
then
    install -m 771 -o 1000 -g 1000 -d /cache/dalvik-cache
fi
return
}

TestCacheSize ()
{
if [ "$cacheSizeBytes" -lt "$MinCacheSize" ];
then
    dataOnlyDex
else
    sysdexOnCache
fi
return
}

if [ "$experimental" = "1" ];
then
    CheckSysDexSize
else 
    TestCacheSize
fi
# TODO add logcat spew
